// Write a program that fails to compile due to lack of memory

void setup() {
  
}
String overwork = "This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap This Feels Kinda Cheap ";
void loop() {

}
